source "https://rubygems.org"

gem "jekyll", "~> 4.4.1"
gem "jekyll-remote-theme", "~> 0.4.3"

group :jekyll_plugins do
  gem "jekyll-asciidoc"
  gem "jekyll-feed"
  gem "jekyll-paginate-v2"
  gem "jekyll-include-cache"
  gem "jekyll-sitemap"
end

gem "logger"
gem "csv"
gem "ostruct"
gem "base64"
gem "bigdecimal"
