name: Gradle Build and Verify
run-name: "Verified ${{ github.repository }} by ${{ github.actor }} with ${{ github.event_name }} (Attempt ${{ github.run_attempt }})"
#.github/workflows/gradle-verify-and-submit.yml

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
      - '[0-9]+-**'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: write

defaults:
  run:
    shell: zsh -l {0}

jobs:

  build-test-submit:
    timeout-minutes: 5
    runs-on: self-hosted
    name: "Build and Test"

    steps:

      - name: "Checkout repository source code"
        uses: actions/checkout@v6.0.2
        timeout-minutes: 1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: "Clean, Build, Test, Submit Dependencies"
        timeout-minutes: 5
        run: |
          source "$SDKMAN_DIR/bin/sdkman-init.sh" || true
          gradle clean build test
